Use realpath() to resolve unresolved path from composer
goaop/framework pull request #295
Opened 2016-09-29 14:27 UTC by RLasinski

Since PR #5174 (https://github.com/composer/composer/pull/5174) the paths from composer can have dots in the paths. This isn't handled by AopComposerLoader.
CachePathManager tries to replace a resolved appPath with an unresolved resourcePath.
e.g. /app/ .... /vendor/composer/../../app

My solution isn't optimal, because *realpath()* is called for every included file.

2016-10-26 07:27 UTC, lisachenko commented
Hi, your path looks valid for PHP>=5.6 after changes in the composer. However, could you please replace `realpath()` with `PathResolver::realpath()` that can work even with non-standard paths from phar archivers, etc...

2016-11-10 09:04 UTC, jcchavezs commented
+1

2016-12-12 17:56 UTC, lisachenko requested changes

2016-12-12 17:56 UTC, lisachenko commented on src/Instrument/ClassLoading/AopComposerLoader.php
> +            $file = realpath($file)?:$file;
Could you please replace `realpath()` with `PathResolver::realpath()`?

2016-12-13 07:08 UTC, lisachenko approved these changes

2016-12-13 07:08 UTC, merged

2016-12-13 07:09 UTC, lisachenko commented
Merged, thanks!