Add path wildcard feature to Enumerator
goaop/framework pull request #300
Opened 2016-11-22 14:03 UTC by icanhazstring

Add wildcard possibility for `includePaths` and `excludePaths`

2016-11-23 06:51 UTC, lisachenko commented
Hi! Thank you for your job! I'll review it soon

2016-11-23 10:00 UTC, icanhazstring commented
@lisachenko can you merge this into the 1.x version line as well?
Problem ist for example we currently can only use PHP<=5.5 - but with then 2.x version line PHP>5.6 is required.

So this needs to be merged into both versions - if possible

2016-11-23 11:16 UTC, lisachenko requested changes

2016-11-23 11:16 UTC, lisachenko commented on src/Instrument/FileSystem/Enumerator.php
> +                    if (preg_match('%' . $includePattern . '%', $filePath)) {
I have a worry, that `preg_match()` could be slow for checking a lot of files during class loading of big framework. Could you please check, if `fnmatch()` could be faster than `preg_match()`.

2016-11-23 11:16 UTC, lisachenko commented on src/Instrument/FileSystem/Enumerator.php
> +    protected function parseWildcardPath($path)
This function can be replaced with built-in `fnmatch()`, see [fnmatch() function](http://php.net/manual/en/function.fnmatch.php)

2016-11-23 11:16 UTC, lisachenko commented on tests/Go/Instrument/FileSystem/EnumeratorTest.php
> +        static::$fixtureBasePath =  realpath(TEST_DIRECTORY) . DIRECTORY_SEPARATOR . 'fixtures';
Oh, it's an armed gun ) Because for several cases `realpath()` can return false which will equal to the empty string. Maybe we can use VFS filesystem for safe tests?

2016-11-23 11:16 UTC, lisachenko commented on tests/Go/Instrument/FileSystem/EnumeratorTest.php
> +        exec('rm -rf ' . static::$fixtureBasePath);
Very dangerous command, I think VFS will be better to use, because who knows if `static::$fixtureBasePath` will equal to the '/'?

2016-11-23 11:19 UTC, lisachenko commented
@icanhazstring changed the base to 1.x, please don't forget to rebase your local branch as well

2016-11-23 11:53 UTC, icanhazstring commented on src/Instrument/FileSystem/Enumerator.php
> +                    if (preg_match('%' . $includePattern . '%', $filePath)) {
Problem is that fnmatch does not work with multiple subfolders. so `/base/*/test` only includes `/base/sub/test` but not `/base/sub/sub/test`

2016-11-23 13:09 UTC, lisachenko commented on src/Instrument/FileSystem/Enumerator.php
> +                    if (preg_match('%' . $includePattern . '%', $filePath)) {
Please, see: https://3v4l.org/iPR39#output Your case is second line

2016-11-24 11:24 UTC, icanhazstring commented on src/Instrument/FileSystem/Enumerator.php
> +                    if (preg_match('%' . $includePattern . '%', $filePath)) {
Well... ok. I'll rewrite it then :)

2016-11-28 12:39 UTC, icanhazstring commented
@lisachenko reworked the tests using vfs and using `fnmatch()` for testing path against pattern

2016-11-28 14:05 UTC, lisachenko approved these changes

2016-11-28 14:06 UTC, merged

2016-11-28 14:06 UTC, lisachenko commented
Squashed and merged! Thank you very much! :+1: