Propose PHP <= 5.5
goaop/framework pull request #305
Opened 2016-12-12 15:39 UTC by infabo

Propose PHP <= 5.5 for 1.x branch.

2016-12-12 17:52 UTC, lisachenko commented
Hi, there are errors in the composer.lock, please resolve them.

2016-12-12 17:55 UTC, lisachenko requested changes

2016-12-12 17:55 UTC, lisachenko commented on composer.json
> +        "php": "<=5.5.99",
It's better to use ~5.5.0 here.

2016-12-12 17:55 UTC, lisachenko commented on composer.json
> +        "doctrine/annotations": "<1.3.0",
Please, switch to ~1.2.0

2016-12-13 07:34 UTC, infabo commented on composer.json
> +        "php": "<=5.5.99",
This would restrict the 1.x branch to PHP 5.5 only. Any reasons why not support PHP 5.3 / 5.4?

2016-12-13 07:38 UTC, infabo commented on composer.json
> +        "doctrine/annotations": "<1.3.0",
acknowledged.

2016-12-13 07:39 UTC, infabo commented
Can't find any issues in composer.lock.

2016-12-14 07:42 UTC, lisachenko commented on composer.json
> +        "php": "<=5.5.99",
5.3 and 5.4 are not supported, anyone who wants to use an old version, can switch to 0.x versions.

2016-12-14 11:25 UTC, merged

2016-12-14 11:26 UTC, lisachenko commented
Merged, thanks

2016-12-14 11:43 UTC, lisachenko commented
Also, removed the `composer.lock` file from the repository.