Added workaround for #327
goaop/framework pull request #328
Opened 2017-07-09 13:31 UTC by TheCelavi

As discussed, here is the pull request with Doctrine entities weaving workaround.

- Added doctrine listener that will correct generated metadata
- Added tests (sorry, no 100% code coverage, method `getTraits` is private, so it would be very hard to provide it. In original library, code has 100% code coverage, but I didn't wanted to add more dependencies)
- Modified README.md, added section about this issue and support

TODO:
- Add support for Symfony' bundle: Event subscriber will be always disabled by default (in order to improve performance). When it is enabled, compiler pass will check if there is a Doctrine ORM enabled in Symfony project, and if there is, it will register event subscriber.

2017-07-11 08:47 UTC, TheCelavi commented on tests/Go/Aop/Bridge/Doctrine/MetadataLoadInterceptorTest.php
> +class Entity__AopProxied
I can not fix this, except to pull out to separate files - however, this class is used only for this test suite, so usual practice is to place it inline within test suite. 

Class name must stay same, that is clear.

2017-07-11 08:47 UTC, TheCelavi commented on tests/Go/Aop/Bridge/Doctrine/MetadataLoadInterceptorTest.php
> +trait SimpleTrait
I can not fix this, except to pull out to separate files - however, this class is used only for this test suite, so usual practice is to place it inline within test suite.

2017-07-11 08:50 UTC, lisachenko requested changes

2017-07-11 08:50 UTC, lisachenko commented on src/Bridge/Doctrine/MetadataLoadInterceptor.php
> + * @package Go\Bridge\Doctrine
Please, drop this auto-generated tag.

2017-07-11 08:50 UTC, lisachenko commented on src/Bridge/Doctrine/MetadataLoadInterceptor.php
> +            $metadata->customRepositoryClassName = null;
it would be nice to have variables aligned.

2017-07-11 08:50 UTC, lisachenko commented on tests/Go/Aop/Bridge/Doctrine/MetadataLoadInterceptorTest.php
> +trait SimpleTrait
We can ignore this, ok

2017-07-12 11:44 UTC, lisachenko approved these changes

2017-07-12 11:46 UTC, merged

2017-07-12 11:48 UTC, lisachenko commented
Squashed and merged, thanks!