Feature/detecting inconsistent weaving
goaop/framework pull request #346
Opened 2017-08-16 09:12 UTC by TheCelavi

@lisachenko Bad weaving is not possible to detect in runtime.

But it is possible to detect it via command. If there is a "bad" weaving (circular references and what now) -> generated proxies will vary. 

So -> at least, we can provide a command utility that can help in debugging.

Need to do some code cleanup - but I would like you to checkout idea and see if we are on same page.

2017-08-16 13:45 UTC, lisachenko requested changes

2017-08-16 13:45 UTC, lisachenko commented on tests/Go/Functional/BaseFunctionalTest.php
> +        self::{$assert}($process->isSuccessful(), sprintf('Unable to execute "%s" command, got output: "%s".', $command, $process->getOutput()));
Better not to use dynamic static method, just write if..else construction, it will be more readable

2017-08-16 13:45 UTC, lisachenko commented on tests/Go/Console/Command/DebugWeavingCommandTest.php
> +class DebugWeavingCommandTest extends BaseFunctionalTest
I'm trying to understand this test, how it's possible to weave differently each time?

2017-08-16 13:45 UTC, lisachenko commented on tests/Fixtures/project/src/Aspect/InconsistentlyWeavingAspect.php
> +    public function __construct(InconsistentlyWeavedClass $problematicClass)
Ah, yes )) Injection of intercepted class, please leave a note about this edge-case in the doc block and link to the issue on github why this happen.

2017-08-16 13:45 UTC, lisachenko commented on tests/Fixtures/project/src/Aspect/InconsistentlyWeavingAspect.php
> +     * @Pointcut\After("execution(public Go\Tests\TestProject\Application\InconsistentlyWeavedClass->badlyWeaved(*))")
Make a note here as well, that we are trying to intercept method from the class that we want to use in the current aspect.

2017-08-16 13:45 UTC, lisachenko commented on src/Console/Command/DebugWeavingCommand.php
> + * Console command for querying an information about aspects
Doc block should be changed according to the functionality of current command

2017-08-16 13:45 UTC, lisachenko commented on src/Console/Command/DebugWeavingCommand.php
> +        $warmer = new CacheWarmer($this->aspectKernel, new NullOutput());
Please, enable assignment alignment for the project in your IDE

2017-08-16 13:45 UTC, lisachenko commented on src/Console/Command/DebugWeavingCommand.php
> +    protected function execute(InputInterface $input, OutputInterface $output)
Idea is clever 👍

2017-08-16 13:45 UTC, lisachenko commented on src/Console/Command/DebugWeavingCommand.php
> +                $io->writeln(sprintf('<fg=white;bg=red;options=bold>[ERR]</>: Proxy on path "%s" is generated on second "warmup" pass.', $path));
Maybe just switch to `$io->error()` or `$io->caution()` here? Instead of manual formatting?

2017-08-16 13:45 UTC, lisachenko commented on src/Console/Command/DebugWeavingCommand.php
> +            $io->writeln(sprintf('<fg=green;options=bold>[OK]</>: <comment>Proxy  on path "%s" is consistently weaved.</comment>', $path));
Suggest is to use `$io->success()` or we can define our own formatting style. It's always cool to separate templating code from the data.

2017-08-16 13:45 UTC, lisachenko commented on src/Console/Command/DebugWeavingCommand.php
> +            return -1;
Typically, exit codes are greater than zero, maybe switch to non-zero positive number?

2017-08-16 13:45 UTC, lisachenko commented on src/Console/Command/DebugWeavingCommand.php
> +        $io->success('Weaving is stabile, there are no errors reported.');
Typo: stabile => stable.

2017-08-16 13:45 UTC, lisachenko commented on src/Console/Command/DebugWeavingCommand.php
> +    private function getProxies(CachePathManager $cachePathManager)
Missed doc block for the method?

2017-08-16 13:45 UTC, lisachenko commented on src/Console/Command/DebugWeavingCommand.php
> +        $proxies = [];
Assignment alignment 😄

2017-08-16 13:51 UTC, TheCelavi commented
I did setup this project for assignment alignment, I just forgot to do reformatting. 

I want to cleanup more these functional tests and to make their usage quite easy for us, we are really getting benefits from them - like, it is really, really easy to construct edge case, to test it, and to make a patch for it.

Ok, cool! Glad you like the idea, I think that, beside documentation, it is quite important that it is possible to debug these kind of issues.

It solves this one: https://github.com/goaop/goaop-symfony-bundle/issues/15, per example...

2017-08-17 13:21 UTC, TheCelavi commented on tests/Go/Functional/BaseFunctionalTest.php
> +        $commandStatement = sprintf('GO_AOP_CONFIGURATION=%s php %s %s %s %s',
Not applicable.

2017-08-17 13:29 UTC, TheCelavi commented
@lisachenko Ok, code cleanup is done, I have optimized all functional tests as well. 

Almost everything is implemented from: https://github.com/goaop/framework/issues/340, there is:

- `assertClassIsWeaved($class)`
- `assertClassIsNotWeaved($class)`

I am planning to implement

- `assertClassHasStaticMethodJoinPoint($class, $methodName, $joinPoint, $index = null)`
- `assertClassHasMethodJoinPoint($class, $methodName, $joinPoint, $index = null)`

and some more methods, as needed. But I will do that in different PR - this can be merged.

2017-08-17 13:51 UTC, lisachenko commented
@TheCelavi  Looks good now!

PS. Just noticed that the verb "weave" is irregular, so correct form for "class is weaved" is "class was woven".

There are many places in the source code with "weaved" :(. Should we adjust your method naming to the correct one right now? Or in separate PR?
  - assertClassWasWoven($className)
  - assertClassWasNotWoven($className)

2017-08-17 13:54 UTC, lisachenko approved these changes

2017-08-17 13:54 UTC, TheCelavi commented
Noup, it is easy-peasy, fixed, thanks!

2017-08-17 14:14 UTC, lisachenko commented
HHVM has segfaulted on Travis-CI :) Time to remove it from matrix... Only delays check.

2017-08-17 14:21 UTC, merged

2017-08-17 14:22 UTC, lisachenko commented
Squashed and merged, thanks!