fix error with "self" references in top level ns
goaop/framework pull request #397
Opened 2018-06-07 21:24 UTC by daniel-sc

This fixes an error when a class with top level namespace uses `self::` to reference a class constant.

The error manifests for example as: 
```
PHP Parse error:  syntax error, unexpected '\' (T_NS_SEPARATOR), expecting identifier (T_STRING)
```

2018-06-07 21:32 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/goaop/framework/inspections/256cb859-8398-4d1f-9454-837e91897b0f) completed: **No new issues**

2018-06-08 05:34 UTC, TheCelavi commented on .gitignore
> +.idea
This should go to your global gitignore. 

See, per example, this: https://gist.github.com/subfuzion/db7f57fff2fb6998a16c but you can find a loot of resources on this topic.

Point here is - rules for ignoring IDE specific files (or system specific files) should not be part of .gitignore files, as we could get into a really large .gitignore files.

2018-06-08 05:35 UTC, TheCelavi requested changes
Please revert .gitignore file.

2018-06-08 07:05 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/goaop/framework/inspections/a8221057-e0e2-4cf5-95b3-233ececf54f2) was created.

2018-06-08 07:08 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/goaop/framework/inspections/a8221057-e0e2-4cf5-95b3-233ececf54f2) completed: **No new issues**

2018-06-08 07:14 UTC, daniel-sc commented
Hi @TheCelavi,
I reverted the .gitignore, but for unclear reasons the AppVeyor build fails no (was working before) - could you maybe restart the build?

2018-06-08 14:25 UTC, lisachenko commented
AppVeyor is buggy and crappy, so we could ignore this fail.

2018-06-08 14:27 UTC, lisachenko commented
I think it would be nice to target 2.x branch, because master is not ready yet, so small patch could be released from 2.x

2018-06-08 14:44 UTC, daniel-sc commented
@lisachenko `2.x` and a new release would be perfect!
Can you merge, or do you need any thing else?

2018-06-08 15:19 UTC, merged