Bump phpunit to latest version
goaop/framework pull request #406
Opened 2019-01-11 10:00 UTC by icanhazstring

Also change the test implementation to use new class structure of phpunit.
Remove old configuration settings which are no longer supported.

2019-01-11 10:00 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/goaop/framework/inspections/25ccaeb5-f8f1-4db9-a32c-dec6af98a634) was created.

2019-01-11 10:08 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/goaop/framework/inspections/25ccaeb5-f8f1-4db9-a32c-dec6af98a634) completed: **No new issues**

2019-01-11 10:58 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/goaop/framework/inspections/b376a328-d3a0-4578-a49f-fc08be3e2a7d) was created.

2019-01-11 11:01 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/goaop/framework/inspections/b376a328-d3a0-4578-a49f-fc08be3e2a7d) completed: **No new issues**

2019-01-11 11:16 UTC, lisachenko requested changes
Nice PR! Thanks!

By the way, could you move FQN `\PhpUnit\Framework\TestCase` to use section to have clean `extends TestCase` string in test classes definitions?

2019-01-11 11:47 UTC, icanhazstring commented
Will do

2019-01-11 15:34 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/goaop/framework/inspections/bc74ed6b-b0c3-4e1f-bff9-75035a69e550) was created.

2019-01-11 15:37 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/goaop/framework/inspections/bc74ed6b-b0c3-4e1f-bff9-75035a69e550) completed: **No new issues**

2019-01-13 09:11 UTC, lisachenko approved these changes
Great job!

2019-01-13 09:13 UTC, merged