AA-0003 fixed the Call to undefined method PhpParser\Node\Expr\Variab…
goaop/framework pull request #417
Opened 2019-04-09 11:56 UTC by ahmed-abid

got this issue :
[Error] Call to undefined method PhpParser\Node\Expr\Variable::toString()

while running some tests using AspectMock caused by this line:

https://github.com/goaop/framework/blob/72521d026692131f4052c1d7b3dad15c846cdd0f/src/Instrument/Transformer/MagicConstantTransformer.php#L94

a suggested solution here: https://github.com/nikic/PHP-Parser/pull/596/files

we can do something here as well as following

2019-04-09 11:56 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/goaop/framework/inspections/8a5623bd-1ec4-4d6b-a2af-f4c81b0d9992) was created.

2019-04-09 12:17 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/goaop/framework/inspections/8a5623bd-1ec4-4d6b-a2af-f4c81b0d9992) completed: **1 new issues**

2019-04-09 14:38 UTC, lisachenko requested changes
Hi, thank you fo sending this PR, please fix small notice in it.

2019-04-09 14:38 UTC, lisachenko commented on src/Instrument/Transformer/MagicConstantTransformer.php
> +            if ($methodCallNode->name instanceof \PhpParser\Node\Identifier && $methodCallNode->name->toString() !== 'getFileName') {
Please use import of class name

2019-04-10 06:49 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/goaop/framework/inspections/e2359f04-e41c-484a-8438-4d1c5bb2b7e9) was created.

2019-04-10 06:52 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/goaop/framework/inspections/7a30e27c-832b-4d1b-aef5-ae9e12f43454) was created.

2019-04-10 06:52 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/goaop/framework/inspections/2be81434-3413-4cef-8044-33cd760807f3) was created.

2019-04-10 07:13 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/goaop/framework/inspections/e2359f04-e41c-484a-8438-4d1c5bb2b7e9) completed: **1 new issues**

2019-04-10 07:39 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/goaop/framework/inspections/2be81434-3413-4cef-8044-33cd760807f3) completed: **2 new issues**

2019-04-10 07:41 UTC, ahmed-abid commented on src/Instrument/Transformer/MagicConstantTransformer.php
> +            if ($methodCallNode->name instanceof \PhpParser\Node\Identifier && $methodCallNode->name->toString() !== 'getFileName') {
Please review

2019-04-11 13:57 UTC, lisachenko approved these changes

2019-04-11 13:58 UTC, merged

2019-04-11 13:58 UTC, lisachenko commented
Squashed and merged into master, thank you!

2019-04-18 08:22 UTC, ddinchev commented
@lisachenko I'm also hitting the same issue. Can you release this fix in 2.3.x?

2019-05-10 15:30 UTC, lisachenko commented
@ddinchev This fix was merged into the master branch only, so you should not expect it to be in 2.x branch. Please check **master** branch instead, aka **3.x-dev**