Memory leaks / method invocation side effects.
goaop/framework pull request #422
Opened 2019-07-30 17:33 UTC by badrutdinovrr

First of all, thank you for your awesome framework!
Unfortunately, a method \Go\Aop\Framework\AbstractMethodInvocation::__invoke doesn't free references to method arguments as soon as have been invoked which results in:
1. Memory leaks
2. Unintended side effect: the argument object destructor isn't called.

I hope my small pull request will help your cool project to become a bit better.
Thank you!

2019-07-30 17:33 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/goaop/framework/inspections/1b60e2dc-7426-4adf-ae6a-3d072b4470bd) was created.

2019-07-30 17:57 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/goaop/framework/inspections/1b60e2dc-7426-4adf-ae6a-3d072b4470bd) completed: **No new issues**

2019-07-31 07:55 UTC, lisachenko commented
Hello! Thank you for the PR.

As master branch is not ready for release yet, please rebase your PR on 2.x branch, so I will be able to release a quick patch.

Also, there are some issues in review, please fix them before merging

2019-07-31 10:55 UTC, lisachenko requested changes

2019-07-31 10:55 UTC, lisachenko commented on src/Aop/Framework/AbstractMethodInvocation.php
> +            else {
Put **else** on the previous line after figure bracket.

2019-07-31 10:55 UTC, lisachenko commented on src/Aop/Framework/AbstractMethodInvocation.php
> +                $this->current = null;
Please, align all consecutive assignments. Also, `$this->current `is updated each time in the recursive calls, I'm not sure that your patch support recursive calls. I would suggest to drop this line entirely, clear only arguments and instance variables

2019-07-31 16:31 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/goaop/framework/inspections/30ecd17e-45b7-4f20-bc90-ea14d54febc1) was created.

2019-07-31 16:32 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/goaop/framework/inspections/cb342cd3-2160-4d3c-a33e-5b348906a122) was created.

2019-07-31 16:45 UTC, badrutdinovrr commented
Closing this in favor of #423

2019-07-31 16:45 UTC, closed without merging

2019-07-31 16:54 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/goaop/framework/inspections/30ecd17e-45b7-4f20-bc90-ea14d54febc1) completed: **No new issues**

2019-07-31 17:19 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/goaop/framework/inspections/cb342cd3-2160-4d3c-a33e-5b348906a122) completed: **No new issues**