[Bug-425] Special treatment for initialization advices in order to fi…
goaop/framework pull request #427
Opened 2019-08-11 05:41 UTC by l00k

…x wrong class construction issue

2019-08-11 05:41 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/goaop/framework/inspections/660d403c-3db6-4a7c-a342-fdc079e3abeb) was created.

2019-08-11 06:05 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/goaop/framework/inspections/660d403c-3db6-4a7c-a342-fdc079e3abeb) completed: **No new issues**

2019-08-12 08:27 UTC, lisachenko commented
Hi! PR is being verified and reviewed

2019-08-12 16:02 UTC, lisachenko requested changes
I can consider this PR as a quick-fix, but it can't be merged due to the explicit copy-paste logic for one single case.

We can continue in two ways:
1) you can research how to do this in the `ReflectionConstructorInvocation` + minimum changes in other files to integrate this and update this PR for merge
2) I can write a fix myself and merge it, closing this PR

2019-08-12 16:02 UTC, lisachenko commented on src/Proxy/ClassProxyGenerator.php
> +        // special treatment for init advices
I don't like this extra copy-paste logic only for one type of advices. Should be rewritten in another way. This solution is not good.

2019-08-12 16:02 UTC, lisachenko commented on src/Proxy/ClassProxyGenerator.php
> +    protected static function wrapWithJoinPoints(array $classAdvices, string $className, string $constructorClassName): array
If we follow this way, we It would be nice to give better naming of variables: `$parentClassName` and `$originalClassName` but I think we can leave this code as-is and modify only the `ReflectionConstructorInvocation` to know which class is used now.

2019-08-12 16:08 UTC, lisachenko commented
Also, need to target 2.x branch to release a quick-fix here as well (while waiting for 3.0.0 release)

2019-08-12 17:52 UTC, l00k commented
Yea.. I know that it was not nice solution. Please fix it yourself :)

2019-08-13 12:57 UTC, lisachenko commented
> Yea.. I know that it was not nice solution. Please fix it yourself :)

Close this one in favor of #428.

Anyway, thank you for reporting this and looking into this, because it's rarely used feature.
PS. Previously I had a wish to remove this feature it in the next major )

2019-08-13 12:57 UTC, closed without merging

2019-08-13 20:52 UTC, l00k commented
Ouu no ;) it is useable for DI implementation. It could be done without that, but it is a lot easier with constructor modification.